### ISSUE TITLE
tap on back button BLE device disconnect

### ISSUE THREAD

**Issue by torretorich** [Ficat/EasyBle#16]
When coming back to the home screen from the Bluetooth screen I get “bluetoothGatt: close()” and the BLE device disconnects.
What can I do to solve this problem?

**Comment by Ficat** [comment]
@torretorich You called BleManager#destroy() in Activity#onDestroy()?  BleManger#destroy() will stop scanning and disconnect all connections.

**Comment by torretorich** [comment]
Thanks a lot @Ficat.
