### ISSUE TITLE
Scan options

### ISSUE THREAD

**Issue by sanjeevitinker** [Ficat/EasyBle#17]
i want to set a static service UUID in scan option like this:
`private UUID uuid = UUID.fromString(serviceUUID);`
`BleManager.ScanOptions scanOptions = BleManager.ScanOptions
                .newInstance()
                .scanPeriod(4000)
                .scanDeviceName(null)
                .scanServiceUuids(uuid);`

but it's throw error:

Required type: UUID[]
Provided: UUID

@Ficat how to set array for this ?

**Comment by Ficat** [comment]
@sanjeevitinker prepare a uuid array that contains your device service-uuids, like the following codes:
`        UUID[] uuidArray = new UUID[]{
                UUID.fromString("your service uuid")
        };
`
