### ISSUE TITLE
Writeable vs writable

### ISSUE THREAD

**Issue by tdh8316** [Ficat/EasyBle#2]
https://github.com/Ficat/EasyBle/blob/e03e06a47fcc0920e35b8f5f30289cdb90985e35/sample/src/main/java/com/ficat/sample/MainActivity.java#L319
`writable` seems to be the proper spelling of the word, so I think we should at least support that as an alias to `writeable`.

**Comment by Ficat** [comment]
thank you for your suggestion :)
