### ISSUE TITLE
custom data field to send to device ble center

### ISSUE THREAD

**Issue by mostafa1611** [Ficat/EasyBle#3]
writing custom code to the ble device, can you please add a field where we can add service uuid and character uuid and write hex code to the device?
or just advice me how to use manager to send text to ble using service_uuid and character_uuid
thank you!

**Comment by Ficat** [comment]
using the _write()_ , whose param needs service uuid and characteristic uuid, to send msg to remote device

**Comment by mostafa1611** [comment]
Hi, onConnectSuccess in a service and tried to send a broadcast to activity but never received in activity?

**Comment by Ficat** [comment]
> Hi, onConnectSuccess in a service and tried to send a broadcast to activity but never received in activity?

make sure that u have registered broadcast.  if u want to send connection status msg from service to activity,   you can also use _hanlder_

**Comment by mostafa1611** [comment]
activity:

package com.example.fastble02;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;

import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.util.Log;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Button;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity implements
View.OnClickListener {
    public static final String TAG = "BLELOG";
    private Button btnClick_relay;
    TextView textView_scan_result;

    //**************************************************************************
    BroadcastReceiver updateUIReciver;
    Bundle b;

    IntentFilter filter;
    Intent serviceIntent;
    String device_name="ZL-RELAY01";


    final String CONNECTED_ACTION="service.to.activity.transfer.connected";
    final String
DISCONNECTED_ACTION="service.to.activity.transfer.disconnected";
    final String
CONNECTION_FAILED_ACTION="service.to.activity.transfer.connection_failed";
    final String CONNECTING_ACTION="service.to.activity.transfer.connecting";

    final String CONNECTED="CONNECTED";
    final String DISCONNECTED="DISCONNECTED";
    final String CONNECTION_FAILED="CONNECTION_FAILED";
    final String CONNECTING="CONNECTING...";
    //**************************************************************************

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        btnClick_relay = (Button) findViewById(R.id.button_relay) ;

        btnClick_relay.setOnClickListener(this);


        textView_scan_result = (TextView)
findViewById(R.id.textView_scan_result);;
       // btnClick_relay.setEnabled(false);
        Log.d(TAG, "inside onReceive device name is true.....");
        MyBluetoothPermission permission=new  MyBluetoothPermission(this);
        permission.checkPermissions();


        //**************************************************************************


        IntentFilter filter = new IntentFilter();
        filter.addAction( DISCONNECTED_ACTION);
        filter.addAction(CONNECTION_FAILED_ACTION);
        filter.addAction(CONNECTING_ACTION);
        filter.addAction(CONNECTED_ACTION);

        updateUIReciver = new BroadcastReceiver() {

            public void onReceive(Context context, Intent intent) {
                //UI update here
                String action =intent.getAction();
                if (intent != null) {
                    b = intent.getExtras();
                    String status = b.get("status").toString();
                    Log.d(TAG, "connect():  status :" + status);
                   // textView_scan_result.setText(status);

  /*
if(action.equalsIgnoreCase("service.to.activity.transfer.connected")){
                        textView_scan_result.setText(status);
                    }*/
                    if(action.equalsIgnoreCase(CONNECTED_ACTION)){
                        textView_scan_result.setText(CONNECTED);
                        //btnClick_relay.setEnabled(true);
                    }

                    else if(action.equalsIgnoreCase(DISCONNECTED_ACTION)){
                        textView_scan_result.setText(DISCONNECTED);
                        btnClick_relay.setEnabled(true);
                    }
                    else if(action.equalsIgnoreCase(CONNECTION_FAILED_ACTION)){
                        textView_scan_result.setText(CONNECTION_FAILED);
                        btnClick_relay.setEnabled(true);
                    }
                    else if(action.equalsIgnoreCase(CONNECTING_ACTION)){
                        textView_scan_result.setText(CONNECTING);

                    }

                }

            }
        };
        registerReceiver(updateUIReciver, filter);
        //***********************************************************************************

    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

/*    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }*/
    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.button_relay:
            v.setEnabled(false);
            serviceIntent = new Intent(this.getApplicationContext(),
WorkerIntentService.class);
            this.startService(serviceIntent);
            break;
            default:
                break;
        }
    }


    public void onPause() {
        super.onPause();

        if (updateUIReciver!= null)
            unregisterReceiver(updateUIReciver);
    }

/*    public void onResume() {
        super.onResume();

        IntentFilter filter = new IntentFilter();
        filter.addAction("service.to.activity.transfer");
        registerReceiver(updateUIReciver, filter);
    }*/
}




service:


package com.example.fastble02;

import android.app.Service;
import android.content.Intent;
import android.os.IBinder;

import android.app.IntentService;
import android.bluetooth.BluetoothGatt;
import android.content.Intent;
import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;

import androidx.annotation.Nullable;

import com.clj.fastble.BleManager;
import com.clj.fastble.callback.BleGattCallback;
import com.clj.fastble.callback.BleWriteCallback;
import com.clj.fastble.data.BleDevice;
import com.clj.fastble.exception.BleException;
import com.clj.fastble.utils.HexUtil;


public class WorkerIntentService extends IntentService {
    private static final String TAG = MainActivity.TAG;
    String mMacAddress = "50:8C:B1:6C:45:FF";
    BleDevice mBleDevice = null;
    public String relay_command = "";
    //String off_command = "C5073030303030303030AA";
    String off_command="C5073132333435363738AA";
    String on_command = "C5043132333435363738AA";
    //String on_command = "C5043030303030303030AA";

    long pressDelay = 5000;
    String msg_from_activity="";
    //Intent local;

    final String CONNECTED_ACTION="service.to.activity.transfer.connected";
    final String
DISCONNECTED_ACTION="service.to.activity.transfer.disconnected";
    final String
CONNECTION_FAILED_ACTION="service.to.activity.transfer.connection_failed";
    final String CONNECTING_ACTION="service.to.activity.transfer.connecting";

    final String CONNECTED="CONNECTED";
    final String DISCONNECTED="DISCONNECTED";
    final String CONNECTION_FAILED="CONNECTION_FAILED";
    final String CONNECTING="CONNECTING...";




    public WorkerIntentService() {
        super("WorkerIntentService");;
    }


    @Override
    public void onCreate() {
        super.onCreate();
        Log.d(TAG, "onCreate: .................................");
        initBleManager();
        //connect();
    }

    @Override
    protected void onHandleIntent(@Nullable Intent intent) {
        Log.d(TAG, "onHandleIntent: ...............................");
    }

    @Override
    public int onStartCommand(@Nullable Intent intent, int flags, int startId) {
        broadcastMessageToActivity(CONNECTING_ACTION,CONNECTING);
        connect();

        sleep(7000);
        if(isConnected()){

        }
       switchOnOffRelay();
        return START_STICKY;
    }

    @Override
    public void onDestroy() {
        Log.d(TAG, "onDestroy: .................................");
        super.onDestroy();
    }

/*    @Override
    public void onStart(@Nullable Intent intent, int startId) {
        Log.d(TAG, "onStart: .............................................");
        super.onStart(intent, startId);
    }*/

    public void initBleManager(){
        BleManager.getInstance().init(this.getApplication());//getApplication());

        BleManager.getInstance().enableLog(true)
                .setReConnectCount(1, 5000)
                .setConnectOverTime(20000)
                .setOperateTimeout(5000)
                .enableBluetooth();
        Log.d(TAG, "onCreate:
isSupportBle():"+BleManager.getInstance().isSupportBle());
    }
    public void writeOff(){
        BleManager.getInstance().write(
                mBleDevice,"0000ffe0-0000-1000-8000-00805f9b34fb",
                "0000ffe1-0000-1000-8000-00805f9b34fb",
                com.clj.fastble.utils.HexUtil.hexStringToBytes(off_command),
                new BleWriteCallback() {

                    @Override
                    public void onWriteSuccess(final int current,
final int total, final byte[] justWrite) {
                        new Handler(Looper.getMainLooper()).post(new
Runnable() {
                            public void run() {
                                Log.d(TAG, "run: write success,
current: " + current
                                        + " total: " + total
                                        + " justWrite: " +
com.clj.fastble.utils.HexUtil.formatHexString(justWrite, true));

                            }
                        });
                    }

                    @Override
                    public void onWriteFailure(final BleException exception) {
                        new Handler(Looper.getMainLooper()).post(new
Runnable() {
                            public void run() {
                                Log.d(TAG, "run: BleException
exception:"+exception.toString());

                            }
                        });
                    }
                });

    }
    public void writeOn(){
        BleManager.getInstance().write(
                mBleDevice,"0000ffe0-0000-1000-8000-00805f9b34fb",
                "0000ffe1-0000-1000-8000-00805f9b34fb",
                com.clj.fastble.utils.HexUtil.hexStringToBytes(on_command),
                new BleWriteCallback() {

                    @Override
                    public void onWriteSuccess(final int current,
final int total, final byte[] justWrite) {
                        new Handler(Looper.getMainLooper()).post(new
Runnable() {
                            public void run() {
                                Log.d(TAG, "writeOn():
onWriteSucces(): " + current
                                        + " total: " + total
                                        + " justWrite: " +
HexUtil.formatHexString(justWrite, true));
                            }
                        });
                    }

                    @Override
                    public void onWriteFailure(final BleException exception) {
                        new Handler(Looper.getMainLooper()).post(new
Runnable() {
                            public void run() {
                                Log.d(TAG, "writeOn():
onWriteFailure(): BleException exception:"+exception.toString());
                            }
                        });
                    }
                });
    }
    public void sleep(long millis){
        try {
            Thread.sleep(millis);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }


    public void connect() {

        Log.d(TAG, "connect(): isConnected():"+isConnected());
        BleManager.getInstance().connect(mMacAddress, new BleGattCallback() {
            @Override
            public void onStartConnect() {
                Log.d(TAG, "connect():  onStartConnect: starting
connection successfuly ..................");

            }

            @Override
            public void onConnectFail(BleDevice bleDevice,
BleException exception) {
                Log.d(TAG, "connect():  onConnectFail:  failed to connect");

//broadcastMessageToActivity(CONNECTION_FAILED_ACTION,CONNECTION_FAILED);
                failed=true;
            }

            @Override
            public void onConnectSuccess(BleDevice bleDevice,
BluetoothGatt gatt, int status) {
                mBleDevice = bleDevice;
               //broadcastMessageToActivity(CONNECTED_ACTION, CONNECTED);
                connected=true;
                Log.d(TAG, "connect():  onConnectSuccess: device
address :" + bleDevice.getDevice().getAddress()+ "
name"+mBleDevice.getDevice().getName());
/*               sleep(3000);
                switchOnOffRelay();
                BleManager.getInstance().disconnectAllDevice();*/
                }

            @Override
            public void onDisConnected(boolean isActiveDisConnected,
BleDevice bleDevice, BluetoothGatt gatt, int status) {
                Log.d(TAG, "connect():  onDisConnected: disconnected
device..............");
                broadcastMessageToActivity(DISCONNECTED_ACTION,DISCONNECTED);

            }
        });
    }

    public void switchOnOffRelay(){
        Log.d(TAG, "switchOnOffRelay():
.........................................");
        sleep(3000);
        writeOn();
        sleep(pressDelay);
        writeOff();
    }
    public boolean isConnected(){
        return  BleManager.getInstance().isConnected(this.mMacAddress);
    }


    public void broadcastMessageToActivity(String action, String status){
            Intent local = new Intent();
            local.setAction(action);
            local.putExtra("status", status);
            sendBroadcast(local);
        }

}

all broadcast works except from onconnectsuccess

**Comment by mostafa1611** [comment]
Hi,
I am trying to use it wit a bluetooth relay  i need to keep the relay open
for at least 10s i call it pressDelay.
I need to know when connection is established and return it to activity via
broadcastreceiver on put in in a textview in the activity then the user
knows its connected.
Thnks a lot.
Br,
Mostafa

**Comment by Ficat** [comment]
sry i don't get what u mean,  u just want to know connection state in activity?  **BleManager**#_isConnected(address)_ , this method can help u
