### ISSUE TITLE
Not detect BLE device without paired

### ISSUE THREAD

**Issue by DaxeshV** [Ficat/EasyBle#6]
It not detect BLE device without paired. I checked twice. I scan BLE device its not detect but once i paired it manually through phone setting and then rescan it through app and it detect. so without paired its not detect?

- I allowed all required permissions.

**Comment by Ficat** [comment]
Hi Vekariya，EasyBle can scan all ble devices, whether paired or not, because pairing is irrelevant to scanning. As for the situation you said, make sure that the device you scan is ble device and it has started _ble advertising_

**Comment by FlomingInfotech** [comment]
alright. Thank you

**Comment by DaxeshV** [comment]
Alright, Thank you
